name: dimsdk
description: Decentralized Instant Messaging Software Development Kit.
version: 2.1.3
homepage: https://github.com/dimchat/sdk-dart
repository: https://github.com/dimchat/sdk-dart
issue_tracker: https://github.com/dimchat/sdk-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dimp: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
