name: pnf
description: Portable Network File.
version: 0.3.0
homepage: https://github.com/dimchat/sdk-dart
repository: https://github.com/dimchat/sdk-dart
issue_tracker: https://github.com/dimchat/sdk-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
   path: ^1.8.0
   dio: ^5.3.3
   object_key: ^0.1.1
   startrek: ^0.5.2
   mkm: ^1.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
